rewritten crypto[*] to Ruby

diff --git a/cryptomount b/cryptomount
--- a/cryptomount
+++ b/cryptomount
@@ -1,20 +1,47 @@
-#!/bin/bash
+#!/usr/bin/ruby -w
 
 DEVICE="/dev/sda6"
 
-if [[ $EUID -ne 0 ]]; then
-	sudo $0;
-	exit $?
-fi
+def die(*args)
+	STDERR.puts(*args)
+	exit 1
+end
 
-# TODO: rvi kdyz v tech adresarich neco uz je
+if Process.euid != 0
+	exec "sudo", "cryptomount"
+	die "exec failed!"
+end
 
-cryptsetup luksOpen $DEVICE crypto &&
-mount /dev/mapper/crypto /mnt/crypto &&
-mount -o bind /mnt/crypto/downloads /home/prvak/downloads &&
-mount -o bind /mnt/crypto/crypto /home/prvak/crypto &&
-mount -o bind /mnt/crypto/fotky /home/prvak/fotky &&
-mount -o bind /mnt/crypto/.bitcoin /home/prvak/.bitcoin
+if `cryptsetup status crypto` =~ / is inactive\./
+	puts "activating crypto mapping."
+	system "cryptsetup luksOpen #{DEVICE} crypto"
+	# TODO check
+else
+	puts "crypto mapping already active."
+end
 
-su prvak -c fetchmail
-systemctl start postfix
+@mounted_dirs = `mount`.lines.select { |line| line =~ %r{/dev/mapper/crypto} }.map { |line|
+	raise unless line =~ /\A(.+) on (.+) type (.+) \(.+\)\Z/
+	$2
+}
+
+unless @mounted_dirs.include? "/mnt/crypto"
+	puts "mounting /mnt/crypto"
+	system "mount /dev/mapper/crypto /mnt/crypto"
+end
+
+%w{downloads crypto fotky .bitcoin}.each do |mount|
+	if @mounted_dirs.include? "/home/prvak/#{mount}"
+		puts "#{mount} already mounted"
+	else
+		target = "/home/prvak/#{mount}"
+		raise unless File.directory?(target)
+		raise "#{target} is dirty!" unless (Dir.entries(target) - %w{. ..}).empty?
+		puts "mounting #{mount}"
+		system "mount -o bind /mnt/crypto/#{mount} /home/prvak/#{mount}"
+	end
+end
+
+puts "starting mail services"
+system "su prvak -c fetchmail"
+system "systemctl start postfix"
diff --git a/cryptounmount b/cryptounmount
--- a/cryptounmount
+++ b/cryptounmount
@@ -1,16 +1,50 @@
-#!/bin/bash
+#!/usr/bin/ruby -w
 
-if [[ $EUID -ne 0 ]]; then
-	sudo $0;
-	exit
-fi
+def die(*args)
+	STDERR.puts(*args)
+	exit 1
+end
 
-systemctl stop postfix
-killall fetchmail
+if Process.euid != 0
+	exec "sudo", "cryptounmount", *ARGV
+	die "exec failed!"
+end
 
-umount /home/prvak/crypto &&
-umount /home/prvak/downloads &&
-umount /home/prvak/fotky &&
-umount /home/prvak/.bitcoin &&
-umount /mnt/crypto &&
-cryptsetup luksClose crypto
+must_unmount = true
+
+until ARGV.empty?
+	case ARGV.shift
+	when "--just-try"
+		must_unmount = false
+	end
+end
+
+output = `lsof -F pc /dev/mapper/crypto`.strip
+unless output.empty?
+	pids = []
+	require 'set'
+	commands = Set.new
+	output.lines.each do |line|
+		case line[0]
+		when 'p'
+			pids << line[1...line.length].strip.to_i
+		when 'c'
+			commands << line[1...line.length].strip
+		else raise
+		end
+	end
+	message = "There #{pids.size > 1 ? "are" : "is"} #{pids.size} user#{pids.size > 1 ? "s" : ""} of crypto (#{commands.to_a.join(', ')}). Cannot unmount."
+	if must_unmount
+		die message
+	else
+		puts message
+		exit 1
+	end
+end
+
+system "systemctl stop postfix"
+system "killall fetchmail"
+
+# TODO: assert completion.
+system "umount -A /dev/mapper/crypto"
+system "cryptsetup luksClose crypto"
